### PR TITLE
add functionality to click an article and view it

### PR DESCRIPTION
**Pull request by dmp990**

### CODE REVIEW

**Comment by two-triangles** [comment]
Good Afternoon Asad, some wonderful looking stuff here! I have a few comments 

- your design is brilliant. This app is looking fantastic.

 - you single article is made up purely of divs with classNames. This works but it is not very good from an accessibility perspective. HTML5 gives us access to lots of semantic HTML elements that we can use instead of divs. 
 
 - You have done this is other aspects of your app so far as well. It might seem tedious but I would suggest going back through and making all the the divs semantic where possible as Accessibility is something that we must be implemented into our code as much as possible as it is sadly something that often gets overlooked.
 
- your form for selecting the topic is really, it would be nice to still be able to use it when we are on the **topics/:topic endpoint**


- finally, when we are on the page looking at all the articles, **/topics**  isn't reflective of what is being rendered on the screen. We are seeing a list of articles, not topics! 


Fantastic work so far Asad :)

**Comment by dmp990** [comment]
:+1: on it

**Comment by two-triangles** [comment]
One more thing Asad! When you enter an invalid id/id that doesn't exist we aren't using the error that would be sent back from the backend! Have a think how you use the returned error and visualise that to the client :)

**Comment by two-triangles** [comment]
Everything looking good Asad! One little thing - one your single article, when the article initially loads we see some elements waiting to load. Add in a loading component and then you will be good to go and merge :)

**Pull request merged**
